export default {
    '1. Purpose of the Application': '1. Objetivo do Aplicativo',
    "1. Information Collection":"1. Coleta de Informações",
    '2. Eligibility': '2. Elegibilidade',
    '2. Use of Informartion': '2. Uso da informação',
    "3. Information Sharing":"3. Compartilhamento de Informações",
    "3. General Provisions":"3. General Provisions",
    '4. Use of the Application': '4. Uso do Aplicativo',
    "4. Information Security":"4. Segurança de Informações",
    '5. Intellectual Property': '5. Propriedade Intelectual',
    "5. Updates to the Privacy Policy":"5. Atualizações na Política de Privacidade",
    '6. Registration': '6. Registro',
    "6. Contact":"6. Contato",
    '7. User Responsibilities': '7. Responsabilidades do Usuário',
    '8. Company Responsibilities': '8. Responsabilidades da Empresa',
    '9. Application and Website Updates': '9. Atualizações do Aplicativo e Site',
    '10. Termination': '10. Rescisão',
    '11. Updates to Terms and Conditions of Use': '11. Atualizações nos Termos e Condições de uso',
    '12. Contact': '12. Contato',
    '- Ensure that the information provided is accurate and up to date.': '- Garantir que as informações fornecidas sejam precisas e atualizadas.',
    '- Maintain the security of your user account and password.': '- Manter a segurança de sua conta de usuário e senha.',
    '- Ensure that the information provided does not violate the intellectual property rights of the Provider or third parties.': '- Garantir que as informações fornecidas não violem os direitos de propriedade intelectual do Provedor ou de terceiros.',
    '- Comply with applicable laws when using the Application.': '- Cumprir as leis aplicáveis ao usar o Aplicativo.',
    '- Do not attempt to access or interfere with the Application or its related systems or networks.': '- Não tentar acessar ou interferir com o Aplicativo ou seus sistemas ou redes relacionados.',
    '- Maintain the security and privacy of user information.': '- Manter a segurança e privacidade das informações do usuário.',
    '- Provide technical support and Application updates.': '- Fornecer suporte técnico e atualizações do Aplicativo.',
    '- Provide accurate information about the Application and its services.': '- Fornecer informações precisas sobre o Aplicativo e seus serviços.',
    "- Registration information: The application may ask the user to provide their name, email address, password and other relevant registration information.":"- Informações de registro: o aplicativo pode solicitar que o usuário forneça seu nome, endereço de e-mail, senha e outras informações de registro relevantes.",
    "- Vehicle information: The application may collect information about the user's vehicle, including the model, year, brand and other related information.":"- Informações do veículo: o aplicativo pode coletar informações sobre o veículo do usuário, incluindo o modelo, ano, marca e outras informações relacionadas.",
    "- Value information: the application can collect information about the user's expenses related to the vehicle, such as fuel, maintenance and other expenses.":"- Informações de valores: o aplicativo pode coletar informações sobre as despesas do usuário relacionadas ao veículo, como combustível, manutenção e outras despesas.",
    "Additionally, the COMMODUS app may collect non-personal information such as device information, browser information, and other technical information to improve the user experience.":"Additionally, the COMMODUS app may collect non-personal information such as device information, browser information, and other technical information to improve the user experience.",
    "- Provide personalized services to the user.":"- Fornecer serviços personalizados ao usuário.",
    "- Send notifications and alerts to the user about vehicle expenses.":"- Enviar notificações e alertas ao usuário sobre as despesas do veículo.",
    "- Provide analysis and reports on user's vehicle expenses.":"- Fornecer análises e relatórios sobre as despesas do veículo do usuário.",
    "- Improve the quality of the application and the services offered.":"- Melhorar a qualidade do aplicativo e os serviços oferecidos.",
    "- Comply with legal and regulatory obligations.":"- Cumprir obrigações legais e regulatórias.",
    "- With user consent.":"- Com consentimento do usuário.",
    "- To comply with legal and regulatory obligations.":"- Para cumprir obrigações legais e regulatórias.",
    "- To protect the rights, property and security of the application, users and other interested parties.":"- Para proteger os direitos, propriedade e segurança do aplicativo, dos usuários e de outras partes interessadas.",
    "The application will not sell, rent or exchange user personal information for marketing or advertising purposes.":"O aplicativo não venderá, alugará ou trocará informações pessoais do usuário para fins de marketing ou publicidade.",
    "Additionally, the COMMODUS app may collect non-personal information such as device information, browser information, and other technical information to improve the user experience.":"Além disso, o aplicativo COMMODUS pode coletar informações não pessoais, como informações do dispositivo, informações do navegador e outras informações técnicas para melhorar a experiência do usuário.",
    'Access to the application can be done through registration, in which the user must provide accurate and updated information, including their name, email address and password. The user is solely responsible for maintaining the confidentiality of their password and for all activities carried out under their account.': 'O acesso ao aplicativo pode ser feito através de um cadastro, no qual o usuário deve fornecer informações precisas e atualizadas, incluindo seu nome, endereço de e-mail e senha. O usuário é o único responsável por manter a confidencialidade de sua senha e por todas as atividades realizadas em sua conta.',
    'account recover': 'recuperação de conta',
    'actual kilometers': 'quilometragem atual',
    'actual month': 'mês atual',
    'actual password': 'senha atual',
    'air conditioning service': 'serviço de ar condicionado',
    'air filter': 'filtro de ar',
    'air filter price': 'preço do filtro de ar',
    'alcohol': 'álcool',
    'alignment and balancing': 'alinhamento e balanceamento',
    'all vehicles': 'todos os veículos',
    'and': 'e',
    'appearance': 'aparência',
    'appearance expense': 'despesa de aparência',
    'apr': 'abr',
    'ask_dont_registered': 'Ainda não tem cadastro?',
    'ask_forgot_password': 'Esqueceu a senha?',
    'aug': 'ago',
    'average': 'média',
    'back': 'voltar',
    'battery change': 'troca de bateria',
    'biannual': 'bianual',
    'brake maintenance': 'manutenção de freios',
    'brand': 'marca',
    'By agreeing to these Terms, the user acknowledges that they have read and understood its terms and agrees to comply with all rules and regulations established in this document.':'Ao concordar com este Termo, o usuário reconhece que leu e entendeu seus termos e concorda em obedecer a todas as regras e regulamentos estabelecidos neste documento.',
    "By agreeing, the user acknowledges that they have read and understood the Privacy Policy and agree to comply with all rules and regulations established in this document.":"Ao concordar o usuário reconhece que leu e entendeu a Política de Privacidade e concorda em obedecer todas as regras e regulamentos estabelecidos neste documento.",
    'camera': 'câmera',
    'cancel': 'cancelar',
    'carpet cleaning': 'limpeza de carpete',
    'cash flow': 'fluxo de caixa',
    'ceiling cleaning': 'limpeza de teto',
    'change user': 'alterar usuário',
    'changing belts and tensioners': 'troca de correias e tensores',
    'changing spark plugs': 'troca de vela',
    'choice the vehicle': 'escolha o veículo',
    'cleaning plastic areas': 'limpeza de áreas plásticas',
    'color': 'cor',
    'combustion': 'combustão',
    'COMMODUS Company is not responsible for any direct, indirect, special or consequential damages arising from the use of the application, including loss of data or profits.': 'A Empresa COMMODUS não se responsabiliza por quaisquer danos diretos, indiretos, especiais ou consequentes decorrentes do uso do aplicativo, incluindo perda de dados ou lucros.',
    'COMMODUS updates both the application and the website in order to provide performance improvements, fix bugs and make new features available, however, there is no specific frequency, depending on the sole and exclusive decision of its managers.':'O COMMODUS atualiza tanto o aplicativo quanto o site a fim de proporcionar melhorias de desempenho, correção de bugs e disponibilização de novas funcionalidades, porém, não há uma periodicidade específica, dependendo da decisão única e exclusiva de seus gestores.',
    'comparasion of expenses': 'comparativo dos gastos',
    'complete washing': 'lavagem completa',
    'conclude': 'concluir',
    'confirm': 'confirmar',
    'confirm_terms': 'Necessário aceitar os termos',
    'cost reduction': 'redução de gastos',
    'current password not match': 'senha atual não confere',
    'date': 'data',
    'dec': 'dez',
    'diagnosis': 'diagnósticos',
    'diesel': 'diesel',
    'digits': 'dígitos',
    'document': 'documento',
    'document expense': 'despesa de documentação',
    'document name': 'nome do documento',
    'e-mail': 'e-mail',
    'eletric': 'elétrico',
    'empty e-mail': 'email em branco',
    'enter a oil code': 'informe um código de óleo',
    'enter a description': 'informe uma descrição',
    'enter a plate': 'informe um placa',
    'enter a value': 'informe um valor',
    'enter actual kilometers': 'digite a quilometragem atual',
    'enter value': 'Digite o valor',
    'error': 'erro',
    'establishment': 'estabelecimento',
    'exhaust system replacement': 'substituição de escapamento',
    'expense': 'despesa',
    'expense consult': 'consultar despesa',
    'expense description': 'descrição da despesa',
    'expenses details': 'detalhes dos gastos',
    'expenses of the month': 'gastos do mês',
    'feb': 'fev',
    'fuel': 'combustível',
    'fuel expense': 'despesa de combustível',
    'fuel filter': 'filtro de combustível',
    'fuel filter price': 'preço do filtro de combustível',
    'full name': 'nome completo',
    'galery': 'galeria',
    'gasoline': 'gasolina',
    'gold hammer': 'martelinho de ouro',
    'headlight polishing': 'polimento de faróis',
    'hybrid': 'híbrido',
    "i agree with the":"concordo com os",
    'i changed the filter': 'troquei o filtro',
    'If the user has questions about these Terms and Conditions of Use of the COMMODUS application, please contact us by email at contato.commodus@gmail.com.':'Se o usuário tiver dúvidas sobre este Termo e Condições de Uso do aplicativo COMMODUS, entre em contato conosco por e-mail no endereço contato.commodus@gmail.com.',
    "If the user has questions or concerns about this privacy policy or the use of personal information by the COMMODUS application, please contact us by email at contato.commodus@gmail.com.":"Se o usuário tiver dúvidas ou preocupações sobre esta política de privacidade ou sobre o uso das informações pessoais pelo aplicativo COMMODUS, entre em contato conosco por e-mail no endereço contato.commodus@gmail.com.",
    'image': 'imagem',
    'increased spending': 'aumento de gastos',
    'info_first_expense_register': 'Para cadastrar sua primeira despesa basta clicar no ícone indicado pela flecha abaixo.',
    'info_first_vehicle_register': 'Para cadastrar seu primeiro veículo basta clicar no mais indicado pela flecha abaixo.',
    'info_require_email': 'Para ajudar a manter sua conta segura, o COMMODUS precisa saber qual email foi utilizado, para podermos lhe enviar a recuperação de senha.',
    'info_require_password': 'Para garantir a segurança da sua conta, o COMMODUS solicita sua senha atual para proceder com a alteração.',
    'inform the date': 'informe a data',
    'insurance': 'seguro',
    'invalid e-mail': 'email inválido',
    'IPVA': 'IPVA',
    'launch new expense': 'lançar nova despesa',
    'leather hydration': 'hidratação de couro',
    'licensing': 'licenciamento',
    'liter': 'litro',
    'liters': 'litros',
    'logout': 'sair',
    'mechanic': 'mecânica',
    'mechanic expense': 'despesa de mecânica',
    'mileage': 'quilometragem',
    'missing data': 'faltam dados',
    'model': 'modelo',
    'model year': 'ano do modelo',
    'monthly': 'mensal',
    'msg_email_already_registered': 'email já registrado',
    'msg_email_or_password_invalids': 'email ou senha inválido(s)',
    'msg_enter_email': 'informe seu email',
    'msg_enter_full_name': 'informe seu nome completo',
    'msg_enter_password': 'informe sua senha',
    'msg_error_on_save_reminder_km': 'Impossível salvar um lembrete futuro de km para km inferior a km atual do veículo',
    'msg_password_recover_check_email': 'Verifique o email recebido para poder aterar sua senha, depois tente logar novamente com a nova senha.',
    'msg_passords_not_match': 'Senhas informadas são divergentes',
    'msg_successfull_image_inserted': 'Imagem inserida com sucesso!',
    'name': 'nome',
    'new password': 'nova senha',
    'new password confirm': 'confirme a nova senha',
    'next alignment reminder': 'lembrete próximo alinhamento',
    'next balancing reminder': 'lembrete próximo balanceamento',
    'Next exchange (KM)': 'Próxima troca (KM)',
    'next exchange reminder': 'lembrete próxima troca',
    'next oil change': 'próx. troca de óleo',
    'not expected expense type': 'tipo de despesa não esperado',
    'not registered e-mail': 'email não registrado',
    'notification': 'notificação',
    'observations': 'observações',
    'oct': 'out',
    'odometer': 'odômetro',
    'oil': 'óleo',
    'oil brand': 'marca do óleo',
    'oil code': 'código do óleo',
    'oil expense': 'despesa de óleo',
    'oil filter': 'filtro de óleo',
    'oil filter price': 'preço do filtro de óleo',
    'oil validity (months)': 'validade do óleo (meses)',
    'other expense': 'despesa outros',
    'others': 'outros',
    'others services': 'outros serviços',
    'painting': 'pintura',
    'painting glazing': 'vitrificação de pintura',
    'painting crystallization': 'cristalização de pintura',
    'painting revitalization': 'revitalização de pintura',
    'password': 'senha',
    'password confirm': 'confirme a senha',
    'password not match': 'senha não confere',
    'password updating': 'alteração de senha',
    'percentage of expenses': 'porcentagem dos gastos',
    'plate': 'placa',
    'preferred fuel': 'combustível preferido',
    'previous month': 'mês anterior',
    'Price/L': 'Preço/L',
    'privacy policy': 'política de privacidade',
    'quarterly': 'trimestral',
    'recurrency': 'recorrência',
    'register now': 'registre-se',
    'regular washing': 'lavagem normal',
    'reports and charts': 'relatórios e gráficos',
    'revision reminder': 'lembrete de revisão',
    'seat cleaning': 'limpeza de bancos',
    'select a brand': 'selecione uma marca',
    'select a fuel': 'selecione um combustível',
    'select a model': 'selecione um modelo',
    'select a vehicle': 'selecione um veículo',
    'select a year': 'selecione um ano',
    'select the location where your photo is': 'selecione o local em que está a sua foto',
    'semiannual': 'semestral',
    'sep': 'set',
    'service': 'serviço',
    'service description': 'descrição do serviço',
    'service review reminder': 'lembrete revisão do serviço',
    'sig in': 'entrar',
    'sinister recovery': 'recuperação de sinistro',
    'spending from the last 365 days': 'gastos dos últimos 365 dias',
    'start': 'início',
    'suspension repair': 'manutenção da suspensão',
    'successfull updated data': 'dados atualizados com sucesso',
    'successfull updated password': 'senha alterada com sucesso',
    'terms of use': 'Termos de uso',
    "The application aims to make the user's life easier by managing automotive expenses. Allowing users to record and track their vehicle-related expenses such as fuel, maintenance and insurance.": 'O aplicativo tem como objetivo facilitar a vida do usuário com o gerenciamento de despesas automotivas. Permitindo que os usuários registrem e acompanhem suas despesas relacionadas a veículos, como combustível, manutenção e seguro.',
    "The application, including its content and design, is protected by intellectual property laws, including copyrights, trademarks and patents. The user agrees not to copy, reproduce, distribute or create derivative works of the application without the Company's prior written authorization.": 'O aplicativo, incluindo o seu conteúdo e design, é protegido por leis de propriedade intelectual, incluindo direitos autorais, marcas registradas e patentes. O usuário concorda em não copiar, reproduzir, distribuir ou criar obras derivadas do aplicativo sem autorização prévia e por escrito da Empresa.',
    "The Application is intended for user's aged 16 or over. By using the Application, you declare that you are at least 16 years old.": 'O Aplicativo é destinado a usuários com 16 anos ou mais. Ao utilizar o Aplicativo, você declara que tem pelo menos 16 anos.',
    'The COMMODUS Company is responsible for:': 'A Empresa COMMODUS se responsabiliza a:',
    "The COMMODUS application may share user personal information with third parties only in the following circumstances:":"O aplicativo COMMODUS pode compartilhar informações pessoais do usuário com terceiros apenas nas seguintes circunstâncias:",
    "The COMMODUS application uses appropriate technical and organizational measures to protect the user's personal information against unauthorized access, use, disclosure or destruction. The application adopts appropriate information security policies to ensure the confidentiality and integrity of the user's personal information.":"O aplicativo COMMODUS usa medidas técnicas e organizacionais adequadas para proteger as informações pessoais do usuário contra acesso não autorizado, uso, divulgação ou destruição. O aplicativo adota políticas de segurança de informações apropriadas para garantir a confidencialidade e integridade das informações pessoais do usuário.",
    "The COMMODUS application uses the information collected for the following purposes:":"O aplicativo COMMODUS usa as informações coletadas para os seguintes fins:",
    "The COMMODUS application collects the following personal information from users:":"O aplicativo COMMODUS coleta as seguintes informações pessoais dos usuários:",
    "The Company may terminate the user's access to the application at any time, without prior notice, if the user violates these Terms.":'A Empresa pode rescindir o acesso do usuário ao aplicativo a qualquer momento, sem aviso prévio, se o usuário violar este Termo.',
    "This privacy policy may be updated at any time without prior notice. Updates will be effective once the new privacy policy is published on the app. It is the user's responsibility to periodically review this privacy policy to be aware of any changes.":"Esta política de privacidade pode ser atualizada a qualquer momento sem aviso prévio. As atualizações serão efetivas assim que a nova política de privacidade for publicada no aplicativo. É responsabilidade do usuário revisar periodicamente esta política de privacidade para estar ciente de quaisquer alterações.",
    'This Term is governed by Brazilian law and any disputes arising from the use of the application will be resolved by the competent Brazilian courts. If any provision of these Terms is considered invalid or unenforceable.': 'Este Termo é regido pelas leis brasileiras e quaisquer disputas decorrentes do uso do aplicativo serão resolvidas pelos tribunais brasileiros competentes. Se qualquer disposição deste Termo for considerada inválida ou inexequível.',
    'The use of the application is the exclusive responsibility of the user, who must use it in accordance with Brazilian legislation and the rules established in these Terms. The user is solely responsible for the content they post on the application and must ensure that it does not infringe the rights of third parties.': 'O uso do aplicativo é de responsabilidade exclusiva do usuário, que deve utilizá-lo de acordo com a legislação brasileira e com as regras estabelecidas neste Termo. O usuário é o único responsável pelo conteúdo que postar no aplicativo e deve garantir que não infrinja os direitos de terceiros.',
    "This privacy policy describes how the COMMODUS Automotive Expense Management application collects, uses and shares users' personal information. The app aims to help users manage their automotive expenses easily and efficiently. Your privacy is important to us and we are committed to protecting it.":"Esta política de privacidade descreve como o aplicativo COMMODUS de Gerenciamento de Despesas Automotivas coleta, usa e compartilha informações pessoais dos usuários. O aplicativo tem como objetivo ajudar os usuários a gerenciar suas despesas automotivas de forma fácil e eficiente. Sua privacidade é importante para nós e estamos empenhados em protegê-la.",
    "This Term may be updated at any time without prior notice. Updates will be effective as soon as the new Term is published in the application. It is the user's responsibility to periodically review these Terms to be aware of any changes.":'Este Termo pode ser atualizado a qualquer momento sem aviso prévio. As atualizações serão efetivas assim que o novo Termo for publicado no aplicativo. É responsabilidade do usuário revisar periodicamente este Termo para estar ciente de quaisquer alterações.',
    'This Terms of Use is a legal agreement between you and the company COMMODUS, which defines the terms and conditions that govern the use of the application made available by the Company. By using the application, you agree to the terms of this Term. If you do not agree with the terms of this Application, do not use the application.': 'Este Termo de uso é um acordo legal entre você e a empresa COMMODUS, que define os termos e condições que regem o uso do aplicativo disponibilizado pela Empresa. Ao utilizar o aplicativo, você concorda com os termos deste Termo. Se você não concordar com os termos deste Aplicativo, não utilize o aplicativo.',
    'total expenses': 'total de gastos',
    'total value': 'valor total',
    'transfer': 'transferência',
    'tire': 'borracharia',
    'tire expense': 'depesa de borracharia',
    'user': 'usuário',
    'user not found': 'usuário não encontrado',
    'user registration': 'cadastro de usuário',
    'value': 'valor',
    'vehicle': 'veículo',
    'vehicle data': 'dados do veículo',
    'vehicle edit': 'editar veículo',
    'vehicle edition': 'edição de veículo',
    'vehicle register': 'cadastro de veículo',
    'vehicle registration': 'emplacamento',
    'vehicle plate': 'placa do veículo',
    'vehicles': 'veículos',
    'year': 'ano',
    'yearly': 'anual',
    'When using the Application, you are responsible for:': 'Ao usar o Aplicativo, você é responsável por:',
};


