export default {
    'account recover':'recuperação de conta',
    'actual kilometers':'quilometragem atual',
    'actual month':'mês atual',
    'actual password':'senha atual',
    'air conditioning service': 'serviço de ar condicionado',
    'air filter':'filtro de ar',
    'air filter price':'preço do filtro de ar',
    'alcohol':'álcool',
    'alignment and balancing':'alinhamento e balanceamento',
    'all vehicles':'todos os veículos',
    'appearance expense': 'despesa de aparência',
    'apr':'abr',
    'ask_dont_registered':'Ainda não tem cadastro?',
    'ask_forgot_password':'Esqueceu a senha?',
    'aug':'ago',
    'average':'média',
    'back':'voltar',
    'battery change':'troca de bateria',
    'biannual':'bianual',
    'brake maintenance':'manutenção de freios',
    'brand':'marca',
    'camera':'câmera',
    'cancel':'cancelar',
    'carpet cleaning':'limpeza de carpete',
    'cash flow':'fluxo de caixa',
    'ceiling cleaning':'limpeza de teto',     
    'change user':'alterar usuário',
    'changing belts and tensioners':'troca de correias e tensores',
    'changing spark plugs':'troca de vela',
    'choice the vehicle':'escolha o veículo',
    'cleaning plastic areas':'limpeza de áreas plásticas',
    'color':'cor',
    'combustion':'combustão',
    'comparasion of expenses':'comparativo dos gastos',
    'complete washing':'lavagem completa',
    'conclude':'concluir',
    'confirm':'confirmar',
    'cost reduction':'redução de gastos',
    'current password not match':'senha atual não confere',
    'date':'data',
    'dec':'dez',
    'diagnosis':'diagnósticos',
    'diesel':'diesel',
    'digits':'dígitos',
    'document expense': 'despesa de documentação',
    'document name':'nome do documento',
    'e-mail':'e-mail',
    'eletric':'elétrico',
    'empty e-mail':'email em branco',
    'enter a oil code':'informe um código de óleo',
    'enter a description':'informe uma descrição',
    'enter a plate':'informe um placa',
    'enter a value':'informe um valor',
    'enter actual kilometers':'digite a quilometragem atual',
    'enter value':'Digite o valor',
    'error':'erro',
    'establishment':'estabelecimento',
    'exhaust system replacement':'substituição de escapamento',
    'expense':'despesa',
    'expense consult':'consultar despesa',
    'expense description':'descrição da despesa',
    'expenses details':'detalhes dos gastos',
    'expenses of the month':'gastos do mês',    
    'feb':'fev',
    'fuel':'combustível',
    'fuel expense':'despesa de combustível',
    'fuel filter':'filtro de combustível',
    'fuel filter price':'preço do filtro de combustível',
    'full name':'nome completo',
    'galery':'galeria',
    'gasoline':'gasolina',
    'gold hammer':'martelinho de ouro',
    'headlight polishing':'polimento de faróis',
    'hybrid':'híbrido',
    'i changed the filter':'troquei o filtro',
    'image':'imagem',
    'increased spending':'aumento de gastos',
    'info_first_expense_register':'Para cadastrar sua primeira despesa basta clicar no ícone indicado pela flecha abaixo.',
    'info_first_vehicle_register':'Para cadastrar seu primeiro veículo basta clicar no mais indicado pela flecha abaixo.',
    'info_require_email':'Para ajudar a manter sua conta segura, o COMMODUS precisa saber qual email foi utilizado, para podermos lhe enviar a recuperação de senha.',
    'info_require_password':'Para garantir a segurança da sua conta, o COMMODUS solicita sua senha atual para proceder com a alteração.',
    'inform the date':'informe a data',
    'insurance':'seguro', 
    'invalid e-mail':'email inválido',
    'IPVA':'IPVA', 
    'launch new expense':'lançar nova despesa',
    'leather hydration':'hidratação de couro',     
    'licensing':'licenciamento',
    'liter':'litro',
    'liters':'litros',
    'logout':'sair',
    'mechanic expense':'despesa de mecânica',
    'mileage':'quilometragem',
    'missing data': 'faltam dados',
    'model':'modelo',
    'model year':'ano do modelo',
    'monthly':'mensal', 
    'msg_email_already_registered':'email já registrado',
    'msg_email_or_password_invalids':'email ou senha inválido(s)',    
    'msg_enter_email':'informe seu email',
    'msg_enter_full_name':'informe seu nome completo',   
    'msg_enter_password':'informe sua senha',
    'msg_password_recover_check_email':'Verifique o email recebido para poder aterar sua senha, depois tente logar novamente com a nova senha.',
    'msg_passords_not_match':'Senhas informadas são divergentes',
    'msg_successfull_image_inserted':'Imagem inserida com sucesso!',    
    'name':'nome',
    'new password':'nova senha',
    'new password confirm':'confirme a nova senha',
    'next alignment reminder':'lembrete próximo alinhamento',
    'next balancing reminder':'lembrete próximo balanceamento',
    'Next exchange (KM)':'Próxima troca (KM)',
    'next exchange reminder':'lembrete próxima troca',
    'next oil change':'próx. troca de óleo',
    'not expected expense type':'tipo de despesa não esperado',
    'not registered e-mail':'email não registrado',
    'notification':'notificação',
    'observations':'observações',
    'oct':'out',
    'odometer':'odômetro',
    'oil brand':'marca do óleo',
    'oil code':'código do óleo',
    'oil expense':'despesa de óleo',
    'oil filter':'filtro de óleo',
    'oil filter price':'preço do filtro de óleo',
    'oil validity (months)':'validade do óleo (meses)',
    'other expense':'despesa outros',
    'others services':'outros serviços',
    'painting':'pintura',
    'painting glazing':'vitrificação de pintura', 
    'painting crystallization': 'cristalização de pintura', 
    'painting revitalization': 'revitalização de pintura',
    'password':'senha',
    'password confirm':'confirme a senha',
    'password not match':'senha não confere',
    'password updating':'alteração de senha',
    'percentage of expenses':'porcentagem dos gastos',
    'plate':'placa',
    'preferred fuel':'combustível preferido',
    'previous month':'mês anterior',
    'Price/L':'Preço/L',
    'quarterly':'trimestral', 
    'recurrency':'recorrência',
    'register now':'registre-se',
    'regular washing':'lavagem normal',
    'reports and charts':'relatórios e gráficos',
    'revision reminder':'lembrete de revisão',
    'seat cleaning':'limpeza de bancos',
    'select a brand':'selecione uma marca',
    'select a fuel':'selecione um combustível',
    'select a model':'selecione um modelo',
    'select a vehicle':'selecione um veículo',
    'select a year':'selecione um ano',
    'select the location where your photo is':'selecione o local em que está a sua foto',
    'semiannual':'semestral', 
    'sep':'set',
    'service':'serviço',
    'service description':'descrição do serviço',
    'service review reminder':'lembrete revisão do serviço',
    'sig in':'entrar',
    'sinister recovery':'recuperação de sinistro',
    'spending from the last 365 days':'gastos dos últimos 365 dias',
    'start':'início',    
    'suspension repair':'manutenção da suspensão',    
    'successfull updated data':'dados atualizados com sucesso',
    'successfull updated password':'senha alterada com sucesso',
    'total expenses':'total de gastos',
    'total value':'valor total',    
    'transfer':'transferência', 
    'tyre expense':'depesa de borracharia',
    'user':'usuário',
    'user not found':'usuário não encontrado',
    'user registration':'cadastro de usuário',
    'value':'valor',
    'vehicle': 'veículo',
    'vehicle data':'dados do veículo',
    'vehicle edit':'editar veículo',
    'vehicle edition':'edição de veículo',
    'vehicle register':'cadastro de veículo',
    'vehicle registration':'emplacamento',
    'vehicle plate':'placa do veículo',    
    'vehicles':'veículos',
    'year':'ano',
    'yearly':'anual'
};


  